pipeline:
  build_docker_image:
    image: docker:17.12.0
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t image .

  latest_image_to_quay:
    image: docker:17.12.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+jenkins_aws" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/jenkins-docker-aws:latest
      - docker push quay.io/ukhomeofficedigital/jenkins-docker-aws:latest
    when:
      event: push
      branch: master

  tag_image_to_quay:
    image: docker:17.12.0
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+jenkins_aws" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/jenkins-docker-aws:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/jenkins-docker-aws:$${DRONE_TAG}
    when:
      event: tag
